#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v18
# autospec commit: 356da62
#
Name     : libtirpc
Version  : 1.3.5
Release  : 29
URL      : https://sourceforge.net/projects/libtirpc/files/libtirpc/1.3.5/libtirpc-1.3.5.tar.bz2
Source0  : https://sourceforge.net/projects/libtirpc/files/libtirpc/1.3.5/libtirpc-1.3.5.tar.bz2
Summary  : Transport Independent RPC Library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libtirpc-data = %{version}-%{release}
Requires: libtirpc-lib = %{version}-%{release}
Requires: libtirpc-license = %{version}-%{release}
Requires: libtirpc-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : krb5-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Use-vendor-config-files-as-fallback-for-a-stateless-.patch

%description
LIBTIRPC 0.1 FROM SUN'S TIRPCSRC 2.3 29 Aug 1994
This package contains SunLib's implementation of transport-independent
RPC (TI-RPC) documentation.  This library forms a piece of the base of Open Network
Computing (ONC), and is derived directly from the Solaris 2.3 source.

%package data
Summary: data components for the libtirpc package.
Group: Data

%description data
data components for the libtirpc package.


%package dev
Summary: dev components for the libtirpc package.
Group: Development
Requires: libtirpc-lib = %{version}-%{release}
Requires: libtirpc-data = %{version}-%{release}
Provides: libtirpc-devel = %{version}-%{release}
Requires: libtirpc = %{version}-%{release}

%description dev
dev components for the libtirpc package.


%package lib
Summary: lib components for the libtirpc package.
Group: Libraries
Requires: libtirpc-data = %{version}-%{release}
Requires: libtirpc-license = %{version}-%{release}

%description lib
lib components for the libtirpc package.


%package license
Summary: license components for the libtirpc package.
Group: Default

%description license
license components for the libtirpc package.


%package man
Summary: man components for the libtirpc package.
Group: Default

%description man
man components for the libtirpc package.


%prep
%setup -q -n libtirpc-1.3.5
cd %{_builddir}/libtirpc-1.3.5
%patch -P 1 -p1
pushd ..
cp -a libtirpc-1.3.5 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1722007026
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --disable-gssapi \
--enable-authdes
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --disable-gssapi \
--enable-authdes
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1722007026
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libtirpc
cp %{_builddir}/libtirpc-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libtirpc/d4b24d1c1f5dca54717237af8f7caaaa493232f1 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
## install_append content
mkdir -p %{buildroot}/usr/share/defaults/etc
cp doc/netconfig %{buildroot}/usr/share/defaults/etc/netconfig
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/defaults/etc/netconfig

%files dev
%defattr(-,root,root,-)
/usr/include/tirpc/netconfig.h
/usr/include/tirpc/rpc/auth.h
/usr/include/tirpc/rpc/auth_des.h
/usr/include/tirpc/rpc/auth_unix.h
/usr/include/tirpc/rpc/clnt.h
/usr/include/tirpc/rpc/clnt_soc.h
/usr/include/tirpc/rpc/clnt_stat.h
/usr/include/tirpc/rpc/des.h
/usr/include/tirpc/rpc/des_crypt.h
/usr/include/tirpc/rpc/key_prot.h
/usr/include/tirpc/rpc/nettype.h
/usr/include/tirpc/rpc/pmap_clnt.h
/usr/include/tirpc/rpc/pmap_prot.h
/usr/include/tirpc/rpc/pmap_rmt.h
/usr/include/tirpc/rpc/raw.h
/usr/include/tirpc/rpc/rpc.h
/usr/include/tirpc/rpc/rpc_com.h
/usr/include/tirpc/rpc/rpc_msg.h
/usr/include/tirpc/rpc/rpcb_clnt.h
/usr/include/tirpc/rpc/rpcb_prot.h
/usr/include/tirpc/rpc/rpcb_prot.x
/usr/include/tirpc/rpc/rpcent.h
/usr/include/tirpc/rpc/svc.h
/usr/include/tirpc/rpc/svc_auth.h
/usr/include/tirpc/rpc/svc_dg.h
/usr/include/tirpc/rpc/svc_mt.h
/usr/include/tirpc/rpc/svc_soc.h
/usr/include/tirpc/rpc/types.h
/usr/include/tirpc/rpc/xdr.h
/usr/include/tirpc/rpcsvc/crypt.h
/usr/include/tirpc/rpcsvc/crypt.x
/usr/lib64/libtirpc.so
/usr/lib64/pkgconfig/libtirpc.pc
/usr/share/man/man3/bindresvport.3t
/usr/share/man/man3/des_crypt.3t
/usr/share/man/man3/getnetconfig.3t
/usr/share/man/man3/getnetpath.3t
/usr/share/man/man3/getrpcent.3t
/usr/share/man/man3/getrpcport.3t
/usr/share/man/man3/rpc.3t
/usr/share/man/man3/rpc_clnt_auth.3t
/usr/share/man/man3/rpc_clnt_calls.3t
/usr/share/man/man3/rpc_clnt_create.3t
/usr/share/man/man3/rpc_secure.3t
/usr/share/man/man3/rpc_soc.3t
/usr/share/man/man3/rpc_svc_calls.3t
/usr/share/man/man3/rpc_svc_create.3t
/usr/share/man/man3/rpc_svc_err.3t
/usr/share/man/man3/rpc_svc_reg.3t
/usr/share/man/man3/rpc_xdr.3t
/usr/share/man/man3/rpcbind.3t
/usr/share/man/man3/rtime.3t

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libtirpc.so.3.0.0
/usr/lib64/libtirpc.so.3
/usr/lib64/libtirpc.so.3.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libtirpc/d4b24d1c1f5dca54717237af8f7caaaa493232f1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/netconfig.5
