#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libtirpc
Version  : 1.1.4
Release  : 20
URL      : https://sourceforge.net/projects/libtirpc/files/libtirpc/1.1.4/libtirpc-1.1.4.tar.bz2
Source0  : https://sourceforge.net/projects/libtirpc/files/libtirpc/1.1.4/libtirpc-1.1.4.tar.bz2
Summary  : Transport Independent RPC Library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libtirpc-lib
Requires: libtirpc-data
Requires: libtirpc-license
Requires: libtirpc-man
Patch1: 0001-Use-vendor-config-files-as-fallback-for-a-stateless-.patch

%description
LIBTIRPC 0.1 FROM SUN'S TIRPCSRC 2.3 29 Aug 1994
This package contains SunLib's implementation of transport-independent
RPC (TI-RPC) documentation.  This library forms a piece of the base of Open Network
Computing (ONC), and is derived directly from the Solaris 2.3 source.

%package data
Summary: data components for the libtirpc package.
Group: Data

%description data
data components for the libtirpc package.


%package dev
Summary: dev components for the libtirpc package.
Group: Development
Requires: libtirpc-lib
Requires: libtirpc-data
Provides: libtirpc-devel

%description dev
dev components for the libtirpc package.


%package lib
Summary: lib components for the libtirpc package.
Group: Libraries
Requires: libtirpc-data
Requires: libtirpc-license

%description lib
lib components for the libtirpc package.


%package license
Summary: license components for the libtirpc package.
Group: Default

%description license
license components for the libtirpc package.


%package man
Summary: man components for the libtirpc package.
Group: Default

%description man
man components for the libtirpc package.


%prep
%setup -q -n libtirpc-1.1.4
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535839042
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --disable-gssapi
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1535839042
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libtirpc
cp COPYING %{buildroot}/usr/share/doc/libtirpc/COPYING
%make_install
## install_append content
mkdir -p %{buildroot}/usr/share/defaults/etc
cp doc/netconfig %{buildroot}/usr/share/defaults/etc/netconfig
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/defaults/etc/netconfig

%files dev
%defattr(-,root,root,-)
/usr/include/tirpc/netconfig.h
/usr/include/tirpc/rpc/auth.h
/usr/include/tirpc/rpc/auth_des.h
/usr/include/tirpc/rpc/auth_unix.h
/usr/include/tirpc/rpc/clnt.h
/usr/include/tirpc/rpc/clnt_soc.h
/usr/include/tirpc/rpc/clnt_stat.h
/usr/include/tirpc/rpc/des.h
/usr/include/tirpc/rpc/des_crypt.h
/usr/include/tirpc/rpc/key_prot.h
/usr/include/tirpc/rpc/nettype.h
/usr/include/tirpc/rpc/pmap_clnt.h
/usr/include/tirpc/rpc/pmap_prot.h
/usr/include/tirpc/rpc/pmap_rmt.h
/usr/include/tirpc/rpc/raw.h
/usr/include/tirpc/rpc/rpc.h
/usr/include/tirpc/rpc/rpc_com.h
/usr/include/tirpc/rpc/rpc_msg.h
/usr/include/tirpc/rpc/rpcb_clnt.h
/usr/include/tirpc/rpc/rpcb_prot.h
/usr/include/tirpc/rpc/rpcb_prot.x
/usr/include/tirpc/rpc/rpcent.h
/usr/include/tirpc/rpc/svc.h
/usr/include/tirpc/rpc/svc_auth.h
/usr/include/tirpc/rpc/svc_dg.h
/usr/include/tirpc/rpc/svc_mt.h
/usr/include/tirpc/rpc/svc_soc.h
/usr/include/tirpc/rpc/types.h
/usr/include/tirpc/rpc/xdr.h
/usr/include/tirpc/rpcsvc/crypt.h
/usr/include/tirpc/rpcsvc/crypt.x
/usr/lib64/libtirpc.so
/usr/lib64/pkgconfig/libtirpc.pc
/usr/share/man/man3/bindresvport.3t
/usr/share/man/man3/des_crypt.3t
/usr/share/man/man3/getnetconfig.3t
/usr/share/man/man3/getnetpath.3t
/usr/share/man/man3/getrpcent.3t
/usr/share/man/man3/getrpcport.3t
/usr/share/man/man3/rpc.3t
/usr/share/man/man3/rpc_clnt_auth.3t
/usr/share/man/man3/rpc_clnt_calls.3t
/usr/share/man/man3/rpc_clnt_create.3t
/usr/share/man/man3/rpc_secure.3t
/usr/share/man/man3/rpc_soc.3t
/usr/share/man/man3/rpc_svc_calls.3t
/usr/share/man/man3/rpc_svc_create.3t
/usr/share/man/man3/rpc_svc_err.3t
/usr/share/man/man3/rpc_svc_reg.3t
/usr/share/man/man3/rpc_xdr.3t
/usr/share/man/man3/rpcbind.3t
/usr/share/man/man3/rtime.3t

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtirpc.so.3
/usr/lib64/libtirpc.so.3.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/libtirpc/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man5/netconfig.5
